feat: ProductCard 컴포넌트, FeedCard 추가
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #13
Opened 2023-06-12 05:47 UTC by ho-ji

Product Card 컴포넌트와 Feed Card 컴포넌트를 추가합니다.
### 구현내용
- 모든 이미지는 로딩 실패 시, 비어있는 데이터, 잘못된 데이터가 넘어왔을 때 기본이미지를 보여주도록 했습니다.
- line-height는 기본 폰트 사용 시, 1일 경우 하단이 잘리는 이슈가 있어 1.5로 수정했습니다.

#### 상품카드 컴포넌트
- props로 id, image, name, price, time을 받습니다. (여기서 time은 createdAt을 넘겨줘야합니다. )
- 해당 컴포넌트를 클릭 시, 상품 상세 페이지로 이동합니다.
- price는 formatNumberWithComma(price)를 호출하여 3자리단위로 콤마가 들어간 string을 적용합니다.
- time은 formatCreateTime(time)을 호출하여 1분 미만 전/ 몇일 전/ 몇주 전/ 몇 달전/ 오래 전 string으로 변경합니다.

#### 피드카드 컴포넌트
-props로 id, author, content, image, time을 받습니다.(여기서 time은 createdAt을 넘겨줘야합니다. )
- 해당 컴포넌트의 프로필 영역을 클릭 시, 해당 작성자의 프로필 페이지로 이동합니다. (FeedProfile)
- 해당 컴포넌트의 이미지+글을 클릭 시, 해당 피드의 상세 페이지로 이동합니다.(FeedContent)
- 좋아요 버튼은 좋아요/좋아요 취소를 API통신으로 구현해놨습니다.(FeedAction)
- 댓글 버튼을 클릭 시, 해당 피드의 상세페이지로 이동합니다.(FeedAction)
- time은 formatCreateTime(time)을 호출하여 1분 미만 전/ 몇일 전/ 몇주 전/ 몇 달전/ 오래 전 string으로 변경합니다.

### TODO
- FeedCard는 more button 클릭 시 recoil에서 값을 비교하여 본인의 게시글이면 수정/삭제를 타인의 게시글이면 게시글 신고 메뉴가 나오게 추가할 예정입니다.

2023-06-12 05:57 UTC, Limttugi requested changes

2023-06-12 05:57 UTC, Limttugi commented on src/components/Common/Product/Card/ProductCard.jsx
> +          {<img onError={handleError} src={!imageError ? image : NoImage} alt='상품이미지' className={s.image} />}
{} 빼도 될 것 같습니다

2023-06-12 05:57 UTC, Limttugi commented on src/utils/setInstanceHeaders.js
>  export const setInstanceHeaders = token => {
인터셉터 사용 안해서 이 파일 삭제하고 api -> index.js 수정해서 올렸었습니다..!

2023-06-12 05:57 UTC, Limttugi commented on src/components/Common/Feed/Action/FeedAction.jsx
> +  const handleClick = async e => {
api 파일 내에서 에러핸들링 하던데 이 부분에서 한 번 더 할 필요가 있을까요?

2023-06-12 06:00 UTC, ho-ji commented on src/components/Common/Product/Card/ProductCard.jsx
> +          {<img onError={handleError} src={!imageError ? image : NoImage} alt='상품이미지' className={s.image} />}
넵 반영하겠습니다!

2023-06-12 06:02 UTC, ho-ji commented on src/utils/setInstanceHeaders.js
>  export const setInstanceHeaders = token => {
이 부분은 커밋 실수였습니다..! 근데 api -> index.js는 수정됬는데 이 파일 삭제 부분은 커밋에서 누락되셨던 것 같습니다!

2023-06-12 06:03 UTC, Limttugi commented on src/utils/setInstanceHeaders.js
>  export const setInstanceHeaders = token => {
아 헐 맞네요 제가 삭제를 안했었군요 ^-^,,,, 죄송함다 ㅋㅋㅋㅋㅋㅋ삭제해주시면 감사하겠습니다

2023-06-12 06:15 UTC, ho-ji commented on src/components/Common/Feed/Action/FeedAction.jsx
> +  const handleClick = async e => {
비동기 통신이라서 생각없이 try/catch를 썼었는데 준혁님 의견이 맞는것 같습니다! 제거 하고 다시 커밋 하겟습니당~

2023-06-12 06:19 UTC, ho-ji reviewed
@Limttugi PR 리뷰 건 수정하여 재커밋했습니다

2023-06-12 06:21 UTC, Limttugi approved these changes

2023-06-12 06:37 UTC, Seunggyu-Jung approved these changes
확인했습니다! 작업량이 엄청 많으셨군요...ㅠㅠㅠㅠ 고생하셨습니다~!!

2023-06-13 02:42 UTC, tmfdk0213 approved these changes

2023-06-13 02:42 UTC, tmfdk0213 commented on src/utils/formatNumberWithComma.js
> +export default formatNumberWithComma
확인했습니다 고생하셨어요!!!😎💙

2023-06-13 02:48 UTC, merged