feat: FeedMoreButton 컴포넌트 추가
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #18
Opened 2023-06-15 14:25 UTC by ho-ji

피드리스트에서 메뉴 버튼 컴포넌트 추가함

### 로그인한 사용자 정보 atom 수정
- 로그인 성공 시, recoil-persist로 사용자의 accountname값만 로컬스토리지에 저장되도록 수정함

### FeedMoreButton
- recoil-persist의 저장된 사용자의 accountname값과 버튼이 눌린 피드의 author값과 비교하여 본인의 피드 여부를 판정
- 본인의 피드인 경우엔 수정 버튼 드롭메뉴로 나옴
- 수정 버튼 선택 시 게시글 수정페이지로 이동(link는 page주소가 정해지면 수정 필요함) => FeedEditButton 컴포넌트
- 타인의 피드인 경우엔 신고 버튼 드롭메뉴로 나옴
- 신고 버튼 선택 시 신고여부 묻는 모달 창 노출 후, 확인 선택 시 게시글 신고 API 수행 => FeedReportButton 컴포넌트
-- 신고가 성공적으로 수행되었으면 '신고되었습니다' 토스트메시지 노출 => react-hot-toast 라이브러리 사용
- 드롭메뉴는 해당 영역 제외 클릭 이벤트 발생 시, ESC버튼 입력 시, 드롭메뉴 내 버튼 입력 시 닫힘

2023-06-16 02:42 UTC, Seunggyu-Jung approved these changes
확인했습니다~!! 수고하셨습니다!!😁👍

2023-06-17 16:31 UTC, tmfdk0213 approved these changes
확인했습니다 고생하셨어요 ~!!~!!😊👍

2023-06-17 16:38 UTC, Limttugi requested changes

2023-06-17 16:38 UTC, Limttugi commented on src/components/Common/Feed/Action/FeedAction.jsx
> +        <img src={isLike ? fillHeartImg : heartImg} alt='' className={s.image}></img>
alt 빠져있습니다!

2023-06-17 16:38 UTC, Limttugi commented on src/components/Common/Feed/MoreButton/FeedMoreButton.jsx
> +      if (!menuRef.current && moreButtonRef.current.contains(e.target)) {
중괄호 없애는게 코드 가독성이 더 좋을 것 같습니다

2023-06-19 00:21 UTC, Limttugi approved these changes

2023-06-19 00:21 UTC, ho-ji commented on src/components/Common/Feed/MoreButton/FeedMoreButton.jsx
> +      if (!menuRef.current && moreButtonRef.current.contains(e.target)) {
추가했습니다

2023-06-19 00:22 UTC, merged