Daniel component
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #19
Opened 2023-06-19 06:20 UTC by Seunggyu-Jung

6월 19일 PR내역
- Home 컴퍼넌트 따로 제작 : Home컴퍼넌트에 사용되는 피드 및 상품 컴퍼넌트 따로 제작
- 피드 및 상품 페이지에서 사용되는 header컴퍼넌트 따로 제작
- 피드 및 상품 페이지 구현 : 10개씩 새로운 데이터 지속적으로 업로드, 무한 스크롤 구현 / 문제점 : 전반적인 CSS Layout은 잡혀있지 않음
- 페이지 스크롤을 맨 위로 올리는 버튼 컴퍼넌트 구현
- App.jsx에 route할 여러 페이지 추가 / 아직 제작은 하지 않음

2023-06-19 07:18 UTC, ho-ji requested changes
확인부탁드려요

2023-06-19 07:18 UTC, ho-ji commented on src/api/feed.js
> +    throw e
throw e도 동작하긴 할텐데 return e로 통일시켜주실 수 있나여!

2023-06-19 07:18 UTC, ho-ji commented on src/components/Common/Header/ListHeader.jsx
> +    navigate('/feed/edit')
저희 글 수정페이지랑 작성페이지 따로 나누기로 하지 않았었나용?

2023-06-19 07:18 UTC, ho-ji commented on src/components/Common/Header/ProductHeader.module.scss
> +}
코드로 보니 Header별로 중복이 많아서 padding만 달라도 되는 문제면 다른 방법을 고려해볼 수도 있을것같아여

2023-06-19 07:18 UTC, ho-ji commented on src/components/Common/UpBtn/UpBtn.jsx
> +        <img className={s.icon} src={Up} alt='위를 가리키는 검은색 화살표입니다' />
Up 카멜케이스로 조금더 명확한 변수이름 사용 부탁드려요! imageUp, imgUp 등등
그리고 alt는 '위로 가기', '최상단으로' 등등으로 조금더 단순화해도 될것같아요~

2023-06-19 07:18 UTC, ho-ji commented on src/components/Common/UpBtn/UpBtn.jsx
> +    <section onClick={handleClick} className={showButton ? s.up : ''}>
className이 ''이되면 section이 display:block이라 하단에 따로 랜더링 되지 않나용?

2023-06-19 07:18 UTC, ho-ji commented on src/components/Home/ProductList/HomeProduct.jsx
> +      console.log(res)
console로 확인한건 지우고 커밋 부탁드려요!

2023-06-19 07:26 UTC, Seunggyu-Jung commented on src/api/feed.js
> +    throw e
넵넵!! 통일시키겠습니당~!!

2023-06-19 07:27 UTC, Seunggyu-Jung commented on src/components/Common/Header/ListHeader.jsx
> +    navigate('/feed/edit')
edit이 수정인지 몰랐습니다ㅎㅎ;; create로 변경 시켰습니다!!

2023-06-19 07:32 UTC, Seunggyu-Jung commented on src/components/Common/UpBtn/UpBtn.jsx
> +        <img className={s.icon} src={Up} alt='위를 가리키는 검은색 화살표입니다' />
넵! 변수명 변경 및 alt 내용 수정했습니다!

2023-06-19 07:40 UTC, Seunggyu-Jung commented on src/components/Common/UpBtn/UpBtn.jsx
> +    <section onClick={handleClick} className={showButton ? s.up : ''}>
넵! 그래서 css에 display : none 처리된 클래스 하나 더 추가했습니다!

2023-06-19 07:44 UTC, Limttugi requested changes

2023-06-19 07:44 UTC, Limttugi commented on src/components/Common/Product/ProductItemeList/ProductItemList.jsx
> +  const _handleScroll = React.useCallback(handleScroll)
함수명 변경이 필요해보입니다! handleScroll이 2개나 있어서요

2023-06-19 07:44 UTC, Limttugi commented on src/components/Home/FeedList/HomeFeed.jsx
> +    <>
여기를 하나의 section으로 나누고 밑에 section을 다른 div나 ul, ol로 바꾸는게 좋아보입니다!

2023-06-19 07:46 UTC, Seunggyu-Jung commented on src/components/Home/ProductList/HomeProduct.jsx
> +      console.log(res)
넵넵!! 작업한 파일 중 console 내역 제거 했습니다!

2023-06-19 07:50 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductItemeList/ProductItemList.jsx
> +  const _handleScroll = React.useCallback(handleScroll)
넵!! _handleScroll 함수명을 handleScrollEvent로 변경했습니다!

2023-06-19 08:08 UTC, Seunggyu-Jung commented on src/components/Home/FeedList/HomeFeed.jsx
> +    <>
넵넵!! 빈 태그를 section으로 바꿨고, section안에 또다른 section넣는게 바람직하지 않아서 div태그로 바꿨습니다!

2023-06-19 08:14 UTC, Seunggyu-Jung commented on src/components/Common/Header/ProductHeader.module.scss
> +}
그러면 혹시 padding부분을 제외하고 그 외의 부분들은 메인 header에서 받아오는 방식으로 코드를 짤까요?? 그러면 코드양이 확실히 줄 것이라 생각합니다!

2023-06-19 11:47 UTC, Limttugi approved these changes

2023-06-19 11:50 UTC, tmfdk0213 approved these changes
확인했습니다 고생하셨어요오!!

2023-06-19 11:55 UTC, ho-ji commented on src/components/Home/ProductList/HomeProduct.jsx
> +    getPorductList()
지금보니 오탈자가 있네요! getProductList로 수정 부탁드려요

2023-06-19 11:56 UTC, ho-ji commented on src/components/Common/Header/ProductHeader.module.scss
> +}
이 작업은 추후 리팩토링으로 가기로 하셧나용?!

2023-06-20 00:02 UTC, Seunggyu-Jung commented on src/components/Common/Header/ProductHeader.module.scss
> +}
넵!! 글쓰기랑 기타 등등 고려해야할 변수가 좀 많아서 추후에 작업하는 것이 좋다고 생각합니다!!

2023-06-20 00:17 UTC, Seunggyu-Jung commented on src/components/Home/ProductList/HomeProduct.jsx
> +    getPorductList()
헙!! 이걸 어떻게 찾으셨나요..!! 확인하고 수정했습니다!!

2023-06-20 00:27 UTC, ho-ji approved these changes
확인했습니다~ PR제목은 변경부탁드릴게요!

2023-06-20 00:36 UTC, merged