feat: feed 작성 페이지 및 feed 작성 컴퍼넌트 작업,  상품 등록 페이지 및 상품 등록 컴퍼넌트 작업, feed 및 상품을 post하는 API 작업
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #25
Opened 2023-06-22 07:02 UTC by Seunggyu-Jung

# 작업내용
## 1. feed 및 상품 등록 페이지, 컴퍼넌트
- feed를 생성할 수 있는 feed 작성 페이지와 컴퍼넌트를 구현했습니다.
- 상품을 등록할 수 있는 상품 등록 페이지와 컴퍼넌트를 구현했습니다.
- feed 작성 페이지는 contents나 image 둘 중 적어도 한개는 업로드해야 등록할 수 있도록 구현했습니다.(if문 사용)
- 상품 등록 페이지는 image, name, price 셋 중 하나라도 작성하지 않으면 등록할 수 없도록 구현했습니다.(if문 사용)
- input태그의 type=file을 활용하여 사진을 업로드 할 수 있는 기능을 구현했습니다.
- 업로드할 이미지를 미리 볼 수 있는 기능을 구현했습니다.
- feed 작성 페이지에는 최대 3장의 사진까지만 등록 할 수 있으며, 이를 넘어가면 경고문구와 함께 등록을 할 수 없도록 구현했습니다.
- 상품 등록 페이지는 오직 한장만 등록 할 수 있도록 구현했습니다.
-  feed 작성 페이지의 contents에는 최대 300자까지 기입할 수 있도록 구현했습니다.
- 상품 등록 페이지의 name은 최대 30자까지 기입할 수 있도록 구현했습니다.
- 상품 등록 페이지의 price를 세 자리마다 쉼표가 들어가도록 설정했습니다.

## 2. feed 및 상품 등록 API
- feed.js 및 product.js 파일에 각각 feed 와 상품을 등록할 수 있는 post API를 구현했습니다.

# 추가 작업 해야하는 부분
- 상품 등록 컴퍼넌트의 가격이 0원이 입력되어도 등록되지 못하게 막을 예정
- 기타 UI는 팀원들과 상담한 후에 추가로 작업할 예정

2023-06-22 07:49 UTC, ho-ji requested changes
feed와 product가 겹치는 부분은 리뷰를 남기지 않았으니 수정사항있으면 둘다 같이 수정해주세요~

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +import { useState } from 'react'
폴더 위치가 Common/Product안에 있는 이유가 있을까요? 다른 페이지에서 재사용되지 않는 코드라면 components/ProductCreate/ 폴더 생성해서 옮겨주세요! 파일이름도 어차피 jsx파일은 다 Component라 Component는 빼도 될것같아요

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +    }
else if (sendPrice === undefined) {
      window.alert('상품가격을 등록해주세요!')
}
에서도 return으로 종료해버린다하면 이코드에서는 if else문을 사용할 필요가 없습니당!
```suggestion
    if (imageUrl === '') {
      window.alert('상품이미지를 등록해주세요!')
      return
    }
    if (name === '') {
      window.alert('상품명을 등록해주세요!')
      return
    } 
    if (sendPrice === undefined) {
      window.alert('상품가격을 등록해주세요!')
      return
    } 
     const res = await postProductAPI({ link: link, itemName: name, price: sendPrice, itemImage: imageUrl })
     navigate(-1)
  
```
그리고 alert띄우는 것보다 상품이밎, 상품명, 상품가격이 비어있을때 send버튼을 disableButton으로 하고 데이터가 있을때 클릭가능하게 하는게 더 좋은 로직같아요!

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +  const [characterCount, setCharacterCount] = useState(0)
characterCount를 useState로 관리하는 이유가 있나요? name이 useState로 관리되고 있는데 name.length로 바로 접근해도 되지 않나용?

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setPrices(inputPrice.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ','))
저의 formatNumverWithComma 함수는 버림받을 걸까요? ㅜㅜ
formatNumberWithComma(inputPrice) 이렇게 쓰면 되는데...!

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setSendPrice(parseInt(inputPrice))
Price랑 sendPrice를 2개로 관리할 필요가 있을까요? 기본으로 콤마가 안들어간 price를 관리하고, 콤마가 들어간 price가 필요한 시점에 formatNumberWithComma(inputPrice)요런식으로 데이터를 넣어도 되지 않나용?

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +    console.log(res)
console.log는 지워주세요

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +                <img key={index} src={preview} alt={`Preview ${index + 1}`} className={s.imagePreview} />
alt는 한글...! ${index +1}번째 이미지 미리보기 정도 일까요

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.module.scss
> +  padding: 2rem 32rem;
패딩 제거해주세요! 레이아웃 적용하면 필요없습니다~

2023-06-22 07:49 UTC, ho-ji commented on src/pages/FeedCreate.jsx
> +    </>
최상단 요소를 리액트프래그먼트가 아니라 MainLayout으로 잡아주세요! 그러면 header및 Footer도 제거해주시면 됩니다.
 Common/Layout/MainLayout.jsx파일을 보시면 기본 레이아웃을 동일한 마진과 패딩을 주기위해 만들어놓은 컴포넌트가 있습니다!

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.module.scss
> +    }
a11y-hidden은 reset.scss에 정의되어있습니다

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +            <label htmlFor='productPrice' className={s.a11yHidden}>
a11y-hidden은 reset.css에 정의되어 있기때문에
```suggestion
            <label htmlFor='productPrice' className="a11y-hidden">
```
다음과 같이 사용하시면 됩니다

2023-06-22 07:49 UTC, ho-ji commented on src/components/FeedList/FeedCreate/FeedCreateComponent.jsx
> +import { useState } from 'react'
FeedCreate 도 별도의 페이지이기때문에 components/FeedList폴더안에 있는 것은 잘못된 구조인것같습니다.
components에 FeedCreate폴더를 바로 생성해주세요

추가로 Product에서 리뷰남겼던 부분들 Feed에서도 보고 같이 수정부탁드릴게요

2023-06-22 07:49 UTC, ho-ji commented on src/components/FeedList/FeedCreate/FeedCreateComponent.jsx
> +    }
여기도 동일하게 else문이 필요없습니다

2023-06-22 07:49 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +          <SmallButton type='button' onClickEvent={handleSend} className={s.btnSend}>
SmallButton에는 type이 기본으로 button으로 정의되어있습니다! 컴포넌트를 사용할때는 정해지지 않은 props를 사용하셔도 전달되지 않아요!

2023-06-22 08:00 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +          <SmallButton type='button' onClickEvent={handleSend} className={s.btnSend}>
넵! 컴퍼넌트에 있는 props 지웠습니다!

2023-06-22 08:01 UTC, Seunggyu-Jung commented on src/components/FeedList/FeedCreate/FeedCreateComponent.jsx
> +    }
넵! else 문 삭제했습니다!

2023-06-22 08:02 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +          <SmallButton type='button' onClickEvent={handleSend} className={s.btnSend}>
className도 같이 지우신거죠??!

2023-06-22 08:03 UTC, Seunggyu-Jung commented on src/components/FeedList/FeedCreate/FeedCreateComponent.jsx
> +import { useState } from 'react'
넵! 폴더 위치 수정했습니다!

2023-06-22 08:07 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +            <label htmlFor='productPrice' className={s.a11yHidden}>
아하! reset.scss는 이렇게 사용하군요! 수정했습니다!

2023-06-22 08:08 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.module.scss
> +    }
넵! 클래스명 수정했습니다!

2023-06-22 08:09 UTC, Seunggyu-Jung commented on src/pages/FeedCreate.jsx
> +    </>
요건 예지님 pr 받으면 적용 시키겠습니다!

2023-06-22 08:10 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +                <img key={index} src={preview} alt={`Preview ${index + 1}`} className={s.imagePreview} />
넵! 한글로 수정했습니다!

2023-06-22 08:11 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +    console.log(res)
앗! 요부분을 빼먹었군요..!! 삭제했습니다!

2023-06-22 08:41 UTC, tmfdk0213 approved these changes
확인했습니다 고생하셨습니다~!~!

2023-06-22 08:52 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setSendPrice(parseInt(inputPrice))
음...예지님이 짜주신 정규표현식은 완성된 값에는 적용이 되는데, 지속적으로 값이 입력되는 경우에는 제대로 콤마를 못붙이는 듯합니다. 그래서 toString뒤에 .replace(/\D/g, '')을 붙이면 지속적으로 값이 변해도 알맞게 쉼표를 붙이는 정규표현식이 되는 것 같습니다! 
우선 이 표현식으로 사용해서 상태 하나 덜었습니다!!ㅎㅎ

2023-06-22 08:56 UTC, ho-ji commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setSendPrice(parseInt(inputPrice))
정규표현식에 오류있다는 말씀이시죵?? 그러면 formatNumverWithComma 함수 수정하셔도 돼요!

2023-06-22 09:02 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setSendPrice(parseInt(inputPrice))
넵넵!! 그럼 함수 수정해놓겠습니다!!

2023-06-22 14:33 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      setPrices(inputPrice.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ','))
넵!! 해당 함수 수정해서 적용했습니다!!

2023-06-22 14:36 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +  const [characterCount, setCharacterCount] = useState(0)
오! 그런 방법이 있었군요!! 바로 적용시켰습니다!!

2023-06-22 14:41 UTC, Seunggyu-Jung commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +import { useState } from 'react'
재사용성이 없네요!!  피드 생성 폴더랑 같이 커먼에서 컴퍼넌트로 옮기고 폴더명 바꿨습니다!

2023-06-23 00:03 UTC, Limttugi requested changes

2023-06-23 00:03 UTC, Limttugi commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +  const link = '/'
이거 지우고 밑에 리뷰에

2023-06-23 00:03 UTC, Limttugi commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.jsx
> +      const res = await postProductAPI({ link: link, itemName: name, price: sendPrice, itemImage: imageUrl })
link: '/' 해도 됩니다!

2023-06-23 00:03 UTC, Limttugi commented on src/components/Common/Product/ProductCreate/ProductCreateComponent.module.scss
> +    .a11yHidden {
이거 그냥 클래스이름에 a11y-hidden 하면되용

2023-06-23 01:25 UTC, Limttugi approved these changes

2023-06-23 01:33 UTC, ho-ji approved these changes

2023-06-23 02:29 UTC, merged