feat: FeedDetailPage페이지 구현
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #26
Opened 2023-06-23 01:28 UTC by tmfdk0213

2023-06-23 02:31 UTC, Seunggyu-Jung approved these changes
확인했습니다!

2023-06-23 05:08 UTC, Limttugi requested changes

2023-06-23 05:08 UTC, Limttugi commented on src/components/FeedDetail/FeedDetail.jsx
> +  // 피드리스트를 누른다 => 누른 피드리스트에 피드 id를 이동된다
주석빼주세용

2023-06-23 05:08 UTC, Limttugi commented on src/components/FeedDetail/AuthorButtonList/AuthorButtonList.jsx
> +    console.log(res)
콘솔 , 아래 콘솔 빼주세요!

2023-06-23 05:08 UTC, Limttugi commented on src/components/FeedDetail/FeedDetail.jsx
> +    console.log(res)
여기두요

2023-06-23 05:08 UTC, Limttugi commented on src/components/FeedDetail/FeedDetailHeader/FeedDetailHeader.module.scss
> +  margin: 3rem;
margin: 3rem 3rem 3rem 5rem으로 바꿔주세요
margin-left 삭제할 수 있어여

2023-06-23 05:32 UTC, ho-ji requested changes
확인부탁드려요~

2023-06-23 05:32 UTC, ho-ji commented on src/api/feed.js
> +// deletePostAPI({post_id: FeedDetail.post_id})
주석은 삭제해주세요

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/AuthorButtonList/AuthorButtonList.jsx
> +    console.log(res)
console.log 위아래 다 삭제 안되셧어요!

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/FeedDetail.jsx
> +import AuthorButtonList from './AuthorButtonList/AuthorButtonList'
import 순서도 맞춰주시면 좋을 것 같아요~ 외부 > 스타일 > 내장

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/FeedDetail.jsx
> +  // const parmas = useParams() // useParams() === 게시글id
요기 주석 삭제도 안되셧어요~

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/FeedDetail.jsx
> +    console.log(res)
요기 console도 삭제 안되셧어요~

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/FeedDetail.jsx
> +    </>
여기  MainLayout으로 적용하시면 좋을것같아요

2023-06-23 05:32 UTC, ho-ji commented on src/pages/FeedDetail.jsx
> +  )
MainLayout은 여기서 적용하면됩니당

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/AuthorButtonList/AuthorButtonList.jsx
> +    const res = await postCommentsAPI({ id: myInfo._id, content: inputValue })
myInfo._id는 잘못된 정보를 넘겨주고 있는거 아닌가요? API명세  확인해보니 post_id를 넘겨줘야하는거같은데, useParams로 가져온 id를 넘겨줘야할것같습니다! myInfo에 _id정보도 없어도 될것같고요!

2023-06-23 05:32 UTC, ho-ji commented on src/components/FeedDetail/FeedDetail.jsx
> +                  return <p>{comment.content}</p>
key props가 없어도 되나용?

2023-06-24 10:50 UTC, Limttugi approved these changes

2023-06-25 03:52 UTC, Limttugi approved these changes

2023-06-25 16:46 UTC, ho-ji approved these changes
확인했습니다

2023-06-25 16:46 UTC, merged