feat: 프로필 페이지에서 팔로잉/팔로워 리스트 모달 구현 및 프로필 페이지 진입 시 항상 스크롤 최상단 이동 기능 추가
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #28
Opened 2023-06-23 11:48 UTC by ho-ji

프로필 페이지 구현 끝

- 프로필 페이지에서 팔로워, 팔로우 수 선택 시 해당 유저 리스트가 모달로 뜸
- 해당 모달에서 유저 선택 시, 그 유저의 프로필 페이지로 이동함
- 모달은 컴포넌트로 분리했고, ESC입력 시, 바깥영역 선택 시 모달 창이 닫히고 모달창이 떠있는 동안 모달 뒤의 스크롤 막힘.
- 프로필페이지 간 이동 시 스크롤은 항상 최상단으로 이동함
- Profile페이지 내 컴포넌트가 많아져 폴더구조 세분화함

2023-06-24 10:55 UTC, Limttugi requested changes

2023-06-24 10:55 UTC, Limttugi commented on src/components/Profile/List/FeedList/ProfileFeedList.jsx
> -        !res.data.post.length
if문이 가독성이 더 좋을 것 같습니다!

2023-06-24 10:55 UTC, Limttugi commented on src/components/Profile/List/FeedList/ProfileFeedList.jsx
> +    console.log(userFeeds)
console.log 있네요

2023-06-24 10:55 UTC, Limttugi commented on src/components/Common/Modal/Modal.jsx
> +    const handleEscapeKeyDown = e => {
useEffect 밖에다 함수 선언해줘도 좋을 것 같아요

2023-06-24 10:55 UTC, Limttugi commented on src/api/profile.js
> +    console.log(accountname, item)
console.log 있습니다

2023-06-24 10:58 UTC, ho-ji commented on src/components/Profile/List/FeedList/ProfileFeedList.jsx
> -        !res.data.post.length
if문으로 바꿔서 커밋햇어요! 여긴 지워진 코드

2023-06-24 11:02 UTC, ho-ji commented
@Limttugi  수정사항 반영하여 재커밋했습니당

2023-06-24 14:17 UTC, Limttugi approved these changes

2023-06-24 14:49 UTC, Seunggyu-Jung approved these changes
확인했습니다~!! 수고하셨습니다~!!

2023-06-25 16:46 UTC, tmfdk0213 approved these changes
확인했습니다아~!~!

2023-06-25 16:51 UTC, merged