feat: feed, 상품 등록 컴퍼넌트 및 페이지 작업,  feed 및 상품을 post하는 API 작업
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #30
Opened 2023-06-25 09:07 UTC by Seunggyu-Jung

# 작업내용
## 1. feed 및 상품 등록 페이지, 컴퍼넌트
- feed를 생성할 수 있는 feed 작성 페이지와 컴퍼넌트를 구현했습니다.
- 상품을 등록할 수 있는 상품 등록 페이지와 컴퍼넌트를 구현했습니다.
- feed 작성 페이지는 contents나 image 둘 중 적어도 한개는 업로드해야 등록할 수 있도록 구현했습니다.
- 상품 등록 페이지는 image, name, price 셋 중 하나라도 작성하지 않으면 등록할 수 없도록 구현했습니다.
- input태그의 type=file을 활용하여 사진을 업로드 할 수 있는 기능을 구현했습니다.
- 업로드할 이미지를 미리 볼 수 있는 기능을 구현했습니다.
- feed 작성 페이지에는 최대 3장의 사진까지만 등록 할 수 있으며, 상품 등록 페이지는 오직 한장만 등록 할 수 있도록 구현했습니다.
- feed 작성 페이지의 contents에는 최대 300자까지, 상품 등록 페이지의 name은 최대 30자까지 기입할 수 있도록 구현했습니다.
- 등록 페이지 이용을 설명하는 GuideLine 컴퍼넌트를 추가했습니다.
- GuideLine은 처음에 열려있다가 상단을 클릭하면 닫히는 형태로 구현했습니다.(ex,오늘의 집 게시글 등록 UI)
## 2. feed 및 상품 등록 API
feed.js 및 product.js 파일에 각각 feed 와 상품을 등록할 수 있는 post API를 구현했습니다.
# 추가 작업 해야하는 부분
- 기타 UI는 팀원들과 상담한 후에 추가로 작업할 예정

2023-06-25 09:56 UTC, Limttugi approved these changes
글 작성이랑 상세 페이지가 있어야 수정 모달 작업 가능해서 일단 가볍게 체크했습니다!

2023-06-25 09:56 UTC, Limttugi commented on src/components/Common/GuideLine/GuideLine.jsx
> +    setShowList(!showList)
{} 안에 코드가 1줄 일 경우 {} 지워도 됩니다!

2023-06-25 09:56 UTC, Limttugi commented on src/components/Common/GuideLine/GuideLine.jsx
> +          {name} 등록 가이드 보기 <span className={s.sub}>원할한 {name} 발행을 위해 꼭 읽어주세요!</span>
원할한 오타 있습니다!

2023-06-25 09:56 UTC, Limttugi commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +      event.target.value = null
null 필요 없지 않을까용

2023-06-25 10:44 UTC, Seunggyu-Jung commented on src/components/Common/GuideLine/GuideLine.jsx
> +          {name} 등록 가이드 보기 <span className={s.sub}>원할한 {name} 발행을 위해 꼭 읽어주세요!</span>
헉! 수정했습니다!!

2023-06-25 10:48 UTC, Seunggyu-Jung commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +      event.target.value = null
event.target.value = null 처리하지 않으면 값이 파일에 남아서 필요하다고 생각합니다!!

2023-06-25 10:49 UTC, Seunggyu-Jung commented on src/components/Common/GuideLine/GuideLine.jsx
> +    setShowList(!showList)
넵!! 해당 부분은 수정했습니다!!

2023-06-25 12:49 UTC, ho-ji requested changes
확인부탁드려용

2023-06-25 12:49 UTC, ho-ji commented on src/components/Common/GuideLine/GuideLine.jsx
> +import React, { useState } from 'react'
import React 제거해주세요.

2023-06-25 12:49 UTC, ho-ji commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +      price: parseInt(prices.replace(',', '')),
replace필요없지 않나용

2023-06-25 12:49 UTC, ho-ji commented on src/pages/FeedCreate.jsx
> +    <ListLayout>
MainLayout 사용해도 되지 않나용

2023-06-25 12:49 UTC, ho-ji commented on src/pages/ProductCreate.jsx
> +    <ListLayout>
여기도 MainLayout사용해도 상관없지 않나용

2023-06-25 12:49 UTC, ho-ji commented on src/utils/formatNumberWithComma.js
> +    .replace(/\D/g, '')
콤마넣는거 안하시면 .replace(/\D/g,'')는 팔요없는 작업입니다

2023-06-25 12:49 UTC, ho-ji commented on src/components/Common/GuideLine/GuideLine.jsx
> +        </ul>
ul, li태그인 이유가 잇나용

2023-06-25 12:56 UTC, Seunggyu-Jung commented on src/components/Common/GuideLine/GuideLine.jsx
> +import React, { useState } from 'react'
넵! 제거했습니다!

2023-06-25 12:57 UTC, Seunggyu-Jung commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +      price: parseInt(prices.replace(',', '')),
넵! 불필요하니 제거했습니다!

2023-06-25 13:02 UTC, Seunggyu-Jung commented on src/utils/formatNumberWithComma.js
> +    .replace(/\D/g, '')
넵! 원래상태로 원복했습니다!

2023-06-25 13:03 UTC, Seunggyu-Jung commented on src/components/Common/GuideLine/GuideLine.jsx
> +        </ul>
가이드내용이 순차적으로 여러번 반복을 하는 형태라서 ul li태그로 구현했습니다!

2023-06-25 13:07 UTC, Seunggyu-Jung commented on src/pages/FeedCreate.jsx
> +    <ListLayout>
오! MainLayout이 더 깔끔하군요! 수정했습니다!

2023-06-25 13:08 UTC, Seunggyu-Jung commented on src/pages/ProductCreate.jsx
> +    <ListLayout>
넵! 이 부분도 MainLayout이  코드가 더 깔끔해서 수정했습니다!

2023-06-26 02:46 UTC, tmfdk0213 approved these changes
확인했습니다 고생하셨어요!!

2023-06-26 02:49 UTC, ho-ji approved these changes

2023-06-26 04:00 UTC, merged