refactor: 등록 페이지 UI 수정 및 페이지 내 초기화 버튼 추가
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #36
Opened 2023-06-27 02:43 UTC by Seunggyu-Jung

# 작업내용
## 1. feed 및 상품 등록 페이지 UI 수정
- 등록 form에 padding 값을 변경했습니다.
- 등록 버튼의 위치를 가장 오른쪽으로 변경했습니다.
- 각종 오탈자를 수정했습니다.
- 상품 등록 페이지의 상품 금액 입력칸 옆에 '원'단위를 추가했습니다.

## 2. 피드 내용 및 상품 가격 초기화 버튼
- 피드 내용과 상품 가격을 초기화시키는 버튼을 구현했습니다.
- 이미지 초기화 작업은 시간 관계상 추후 리펙토링에서 진행하고자 합니다.

2023-06-27 04:33 UTC, ho-ji requested changes

2023-06-27 04:33 UTC, ho-ji commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +                <SmallButtonDisable>글 비우기</SmallButtonDisable>
이건 수정사항은 아니고 개인적인 의견인데 초기화버튼은 없거나 이미지 버튼이 깔끔할거같긴해요~~

2023-06-27 04:33 UTC, ho-ji commented on src/components/FeedCreate/FeedCreateComponent.jsx
>              <div className={s.counter}>글자 수: {contents.length}/300</div>
div태그인 이유가 잇나요?

2023-06-27 04:40 UTC, Seunggyu-Jung commented on src/components/FeedCreate/FeedCreateComponent.jsx
>              <div className={s.counter}>글자 수: {contents.length}/300</div>
음...딱히 이유는 없었는데 p태그가 더 깔끔하고 시멘틱하네요! 수정했습니다!

2023-06-27 04:41 UTC, Seunggyu-Jung commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +                <SmallButtonDisable>글 비우기</SmallButtonDisable>
음...그래도 300자 넘어가는 내용을 쓰다가 다 지워야할때, 버튼하나만 누르면 다 지워져서 편할 것 같아서 있는게 좋을 듯 합니다!

2023-06-27 05:36 UTC, tmfdk0213 approved these changes
고생많으셨어요~!!

2023-06-27 05:42 UTC, Limttugi requested changes

2023-06-27 05:42 UTC, Limttugi commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +            {onBtn === true ? (
삼항연산자 많이 쓰면 가독성이 떨어집니다!

2023-06-27 05:42 UTC, Limttugi commented on src/components/ProductCreate/ProductCreateComponent.jsx
>      if (imageUrl !== '' && name !== '' && prices !== '') {
한 줄 일 시 {} 빼도 됩니다

2023-06-27 05:42 UTC, Limttugi commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +            {onBtn === true ? (
=== true는 필요 없습니다
onBtn 값이 true / false가 들어가니까요

2023-06-27 06:01 UTC, Seunggyu-Jung commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +            {onBtn === true ? (
넵넵!! !onBtn으로 수정했습니다!

2023-06-27 06:02 UTC, Seunggyu-Jung commented on src/components/ProductCreate/ProductCreateComponent.jsx
>      if (imageUrl !== '' && name !== '' && prices !== '') {
혹시 () 이거 말씀하신건가요??

2023-06-27 06:05 UTC, Limttugi commented on src/components/ProductCreate/ProductCreateComponent.jsx
>      if (imageUrl !== '' && name !== '' && prices !== '') {
아뇨 if문이요!

2023-06-27 06:06 UTC, Seunggyu-Jung commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +            {onBtn === true ? (
아! 그럼 혹시 if문으로 작성하면 될까요??

2023-06-27 06:06 UTC, Seunggyu-Jung commented on src/components/ProductCreate/ProductCreateComponent.jsx
>      if (imageUrl !== '' && name !== '' && prices !== '') {
아! 넵넵! 수정했습니다!

2023-06-27 07:50 UTC, Limttugi commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +            {onBtn === true ? (
네!

2023-06-27 13:05 UTC, Seunggyu-Jung commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +            {onBtn === true ? (
&& 연산자로 조건문 간소화 시켰습니다~!!

2023-06-28 02:38 UTC, ho-ji requested changes

2023-06-28 02:38 UTC, ho-ji commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +              {prices !== '' ? (
'' 빈문자열은 false니까 !prices로 체크할수잇지않나용?

2023-06-28 02:38 UTC, ho-ji commented on src/components/FeedCreate/FeedCreateComponent.jsx
> +              {contents !== '' ? (
여기도 !contents

2023-06-28 02:38 UTC, Limttugi approved these changes

2023-06-28 07:51 UTC, Seunggyu-Jung commented on src/components/ProductCreate/ProductCreateComponent.jsx
> +              {prices !== '' ? (
아! 그렇네요!! 바로 해당 부분말고 비슷한 부분 전부 수정했습니다!

2023-06-28 07:57 UTC, ho-ji approved these changes

2023-06-28 08:19 UTC, merged