feat: Button 컴포넌트 추가
FRONTENDSCHOOL5/final-16-GreenTangerineMarket pull request #4
Opened 2023-06-08 02:21 UTC by tmfdk0213

2023-06-08 04:16 UTC, Limttugi requested changes

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Medium/MediumButton.module.scss
> +  color: #767676;
global scss에 $color-767676 변수 있습니다!!

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Medium/MediumButton.module.scss
> +  background: #c4c4c4;
global scss에 $color-c4c4c4변수 있습니다!!

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Msmall/MsmallButton.module.scss
> +  background: #21bf48;
global scss에 $main-color변수 있습니다!!

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Msmall/MsmallButton.module.scss
> +  border: 1px solid #767676;
global scss에 $color-767676 변수 있습니다!!

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Small/SmallButton.module.scss
> +  color: #767676;
global scss에 $color-767676 변수 있습니다!!

2023-06-08 04:16 UTC, Limttugi commented on src/components/Common/Button/Small/SmallButton.module.scss
> +  width: 8rem;
smallButton, smallButtonDisabled, smallWhiteButton 3개에서 겹치는 css들은 변수처럼 관리할 수 있습니다!
sass의 mixin 이라는게 있는데 참고해보세요!
다른 버튼들도 마찬가지입니당

2023-06-08 04:16 UTC, Limttugi commented on src/pages/FeedList.jsx
> -const FeedList = () => {
이거는 아예 삭제하신 것 같습니다...?

2023-06-08 07:36 UTC, Limttugi approved these changes

2023-06-08 09:10 UTC, Seunggyu-Jung approved these changes
확인했습니다~!! 고생하셨습니다!!

2023-06-09 01:40 UTC, ho-ji approved these changes
확인했습니다~ 다음부턴 커밋컨벤션도 같이 확인부탁드릴게요!

2023-06-09 01:42 UTC, merged